### PR TITLE
Add MeterRatio meter implementation

### PR DESCRIPTION
**Pull request by alex-davidson**
Designed for monitoring a producer/consumer system, exposing the ratio of produced items to consumed. The producer is 'dominant' in that items which were not recorded as produced are not relevant to the metric.

### CODE REVIEW

**Comment by emmaffiondavies** [comment]
~~Additionally blocked until 17.08.~~ (Sprint started)

**Comment by alex-davidson** [comment]
Since this relates to a non-Epro repository, sprint boundaries are largely irrelevant. Besides, it's incomplete.

**Comment by alex-davidson** [comment]
This is really hard to get right. We don't want a numerator mark with no denominator marks to yield infinities because it might be sheer coincidence that it arrives first, causing a spike and triggering alarms. But we do want to know if the denominator is never firing.

**Comment by alex-davidson** [comment]
Closing this for now since no work has been done on it for a long time.

**Pull request closed without merging**
